// <auto-generated />
namespace SimpleMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class empty_to_add_book_seed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(empty_to_add_book_seed));
        
        string IMigrationMetadata.Id
        {
            get { return "201712071659479_empty_to_add_book_seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
